zeebe:
  client:
    broker:
      contactPoint: localhost:26500
    security:
      plaintext: true
    #cloud:
    #  clusterId: d11b358a-4bd4-49d9-9163-97459c494f27
    #  clientId: 6~sasrkuOg9hCezoD3cIeDXjwZvgGRdM
    #  clientSecret: k6JVN4DEoekTSLdaitRxJxdE~_ADgJunjK6Wla_dfr.dz2EahKbT4wQuM0pfLZ5x
    worker:
      defaultName: zeebe-worker
      defaultType: userTask
      adminUsername: demo
      adminPassword: demo
    job:
      timeout: 5000
    requestTimeout: 10000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/zeebe
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  thymeleaf:
    prefix:
      classpath: /templates/
    suffix: .html

server:
  port: 8081